language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t gaeun1116/fullstack-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true gaeun1116/fullstack-test-app npm run test

after_success:
  - docker build -t gaeun1116/docker-frontend ./frontend
  - docker build -t gaeun1116/docker-backend ./backend
  - docker build -t gaeun1116/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gaeun1116/docker-frontend
  - docker push gaeun1116/docker-backend
  - docker push gaeun1116/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-us-east-2-887067101268
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY